### ISSUE TITLE
page not found for reading, Build a Basic CRUD App with Angular 7.0 and Spring Boot 2.1

### ISSUE THREAD

**Issue by AnanthaRajuC** [oktadeveloper/okta-spring-boot-2-angular-7-example#1]
Hyperlink: Build a Basic CRUD App with Angular 7.0 and Spring Boot 2.1
URL: https://github.com/oktadeveloper/okta-spring-boot-2-angular-7-example/blob/master

**Comment by mraible** [comment]
I'm not sure why you want to link to that URL. Here's the article for the blog post: https://developer.okta.com/blog/2018/08/22/basic-crud-angular-7-and-spring-boot-2
